theme: jekyll-theme-primer
title: CS109a Final Project
description: developing a restaurant recommendation engine for Yelp 
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
